import type { ProviderEntry } from "./types";

// Hosting providers - Keep this list simple and append-only; prefer lowercase in aliases
export const HOSTING_PROVIDERS: ProviderEntry[] = [
  {
    name: "Vercel",
    domain: "vercel.com",
    category: "hosting",
    aliases: ["vercel"],
  },
  {
    name: "Netlify",
    domain: "netlify.com",
    category: "hosting",
    aliases: ["netlify"],
  },
  {
    name: "Cloudflare",
    domain: "cloudflare.com",
    category: "hosting",
    aliases: ["cloudflare", "cloudflare registrar"],
  },
  {
    name: "DigitalOcean",
    domain: "digitalocean.com",
    category: "hosting",
    aliases: ["digitalocean"],
  },
  {
    name: "Amazon S3",
    domain: "aws.amazon.com",
    category: "hosting",
    aliases: ["aws", "amazon", "amazon web services", "s3", "amazon s3"],
  },
  {
    name: "GitHub Pages",
    domain: "github.com",
    category: "hosting",
    aliases: ["github pages", "github"],
  },
  {
    name: "Fly.io",
    domain: "fly.io",
    category: "hosting",
    aliases: ["fly.io", "flyio", "fly"],
  },
  {
    name: "Akamai",
    domain: "akamai.com",
    category: "hosting",
    aliases: ["akamai"],
  },
  {
    name: "Heroku",
    domain: "heroku.com",
    category: "hosting",
    aliases: ["heroku"],
  },
  {
    name: "WP Engine",
    domain: "wpengine.com",
    category: "hosting",
    aliases: ["wp engine"],
  },
  {
    name: "WordPress.com",
    domain: "wordpress.com",
    category: "hosting",
    aliases: ["wordpress"],
  },
  {
    name: "Pantheon",
    domain: "pantheon.io",
    category: "hosting",
    aliases: ["pantheon"],
  },
  {
    name: "Squarespace",
    domain: "squarespace.com",
    category: "hosting",
    aliases: ["squarespace"],
  },
  {
    name: "Wix",
    domain: "wix.com",
    category: "hosting",
    aliases: ["wix"],
  },
  {
    name: "Shopify",
    domain: "shopify.com",
    category: "hosting",
    aliases: ["shopify"],
  },
  {
    name: "Webflow",
    domain: "webflow.com",
    category: "hosting",
    aliases: ["webflow"],
  },
  {
    name: "Render",
    domain: "render.com",
    category: "hosting",
    aliases: ["render"],
  },
  {
    name: "Railway",
    domain: "railway.app",
    category: "hosting",
    aliases: ["railway", "railway.app"],
  },
  {
    name: "Firebase Hosting",
    domain: "firebase.google.com",
    category: "hosting",
    aliases: ["firebase", "firebase hosting", "web.app"],
  },
  {
    name: "Google Cloud Storage",
    domain: "cloud.google.com",
    category: "hosting",
    aliases: ["google cloud storage", "gcs", "storage.googleapis.com"],
  },
  {
    name: "Azure Static Web Apps",
    domain: "azure.microsoft.com",
    category: "hosting",
    aliases: ["azure static web apps", "azure static", "azure"],
  },
  {
    name: "GitLab Pages",
    domain: "gitlab.com",
    category: "hosting",
    aliases: ["gitlab pages", "gitlab"],
  },
  {
    name: "OVHcloud",
    domain: "ovhcloud.com",
    category: "hosting",
    aliases: ["ovh", "ovhcloud"],
  },
  {
    name: "Hetzner",
    domain: "hetzner.com",
    category: "hosting",
    aliases: ["hetzner"],
  },
  {
    name: "Linode",
    domain: "linode.com",
    category: "hosting",
    aliases: ["linode"],
  },
];
